- name: check a number less than 10 or not
  hosts: local
  connection: local
  vars:
    NUMBER_OF_SESSIONS: 7
  tasks:
  - name: check Live or not
    ansible.builtin.debug:
      msg: "Yes, more than 5 sessions"
    when: NUMBER_OF_SESSIONS > 5